// <auto-generated />
namespace MonsterHunterCompanion.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddingBiasAndPrimarySkill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingBiasAndPrimarySkill));
        
        string IMigrationMetadata.Id
        {
            get { return "201701290443346_AddingBiasAndPrimarySkill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
