// <auto-generated />
namespace MonsterHunterCompanion.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SkillCorrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkillCorrections));
        
        string IMigrationMetadata.Id
        {
            get { return "201701290519373_SkillCorrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
